apiVersion: v1
kind: Service
metadata:
  name: exercise-app-postgres
  labels:
    app: exercise-app-postgres
spec:
  type: NodePort
  selector:
    app: exercise-app-postgres
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
