apiVersion: v1
kind: Service
metadata:
  name: exercise-postgres
  labels:
    app: exercise-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: exercise-postgres
    tier: postgres
