apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-postgres
  labels:
    app: exercise-postgres
spec:
  selector:
    matchLabels:
      app: exercise-postgres
      tier: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: exercise-postgres
        tier: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
